#pragma once
#define WRITE_N byte(0x00)
#define UPDATE_N byte(0x10)
#define WRITE_N_UPDATE_ALL byte(0x20)
#define WRITEUPDATE_N byte(0x30)
#define POWER_DOWN_N byte(0x40)
#define POWER_DOWN_ALL byte(0x50)
#define SELECT_INT_REF byte(0x60)
#define SELECT_EXT_REF byte(0x70)
#define NO_OPERATION byte(0xf0)